Awesome/Models/ViewModel/HomeViewModel.cs
using System.Collections.Generic;
using System.Linq;
using Awesome.ApiIntegration.JsonGroupStageResult;
using Awesome.Models.DB;
using Awesome.Models.EntityManager;

namespace Awesome.Models.ViewModel
{
    public class HomeViewModel
    {
        public HomeViewModel(JsonGroupStageResult groupStageMatches)
        {
            ResultTable = GetResultTable();
            UserLoginView = new UserLoginView();
            UserSignUpView = new UserSignUpView();
            Matches = TournamentUtility.CreateSchedule(groupStageMatches);
            UsersWithNoBet = UserManager.GetUsersWithNoBet();
            SignupErrorMessage = "";
            LoginErrorMessage = "";

        }
        public string LoginErrorMessage { get; set; }
        public string SignupErrorMessage { get; set; }
        public UserSignUpView UserSignUpView { get; set; }
        public UserLoginView UserLoginView { get; set; }
       public List<Standing> ResultTable { get; set; }
       public List<List<Schedule>> Matches { get; set; }
        public List<User> UsersWithNoBet { get; set; }

    public List<Standing> GetResultTable()
        {
            
            List<Standing> resultTable = new List<Standing>();
            List<User> users = UserManager.GetUsers().Where(x => x.UserBet != null).OrderByDescending(x => x.TotalPoints).ToList();

            foreach (var user in users)
            {
                Standing standing = new Standing();

                SetNumberOfFinals(user, standing);
                SetNumberOfMatches(user, standing);
                standing.LoginName = user.LoginName;
                standing.RealName = string.Format("{0} {1}", user.FirstName, user.LastName);
                standing.TotalPoints = user.TotalPoints;
                resultTable.Add(standing);
            }
        return resultTable;
        }

        public void SetNumberOfMatches(User user, Standing standing)
        {
            int threePoints = 0;
            int onePoints = 0;
            int zeroPoints = 0;
            foreach (var match in user.UserBet.Matches)
            {
                if (match.ResultColor == "green")
                {
                    threePoints += 1;
                }
                if (match.ResultColor == "yellow")
                {
                    onePoints += 1;
                }
                if (match.ResultColor == "red")
                {
                    zeroPoints += 1;
                }
                
                standing.NumberOfThreePoints = threePoints;
                standing.NumberOfOnePoints = onePoints;
                standing.NumberOfZeroPoints = zeroPoints;

            }
        }

        private void SetNumberOfFinals(User user, Standing standing)
        {
            List<string> qualified = new List<string>()
            {
                user.UserBet.Qualified1Color,
                user.UserBet.Qualified2Color,
                user.UserBet.Qualified3Color,
                user.UserBet.Qualified4Color,
                user.UserBet.Qualified5Color,
                user.UserBet.Qualified6Color,
                user.UserBet.Qualified7Color,
                user.UserBet.Qualified8Color,
                user.UserBet.Qualified9Color,
                user.UserBet.Qualified10Color,
                user.UserBet.Qualified11Color,
                user.UserBet.Qualified12Color,
                user.UserBet.Qualified13Color,
                user.UserBet.Qualified14Color,
                user.UserBet.Qualified15Color,
                user.UserBet.Qualified16Color,
            };

            List<string> quarterfinals = new List<string>()
                {
                    user.UserBet.QuarterFinalist1Color,
                    user.UserBet.QuarterFinalist2Color,
                    user.UserBet.QuarterFinalist3Color,
                    user.UserBet.QuarterFinalist4Color,
                    user.UserBet.QuarterFinalist5Color,
                    user.UserBet.QuarterFinalist6Color,
                    user.UserBet.QuarterFinalist7Color,
                    user.UserBet.QuarterFinalist8Color,
                };
            List<string> semiFinals = new List<string>()
                {
                    user.UserBet.Semifinalist1Color,
                    user.UserBet.Semifinalist2Color,
                    user.UserBet.Semifinalist3Color,
                    user.UserBet.Semifinalist4Color,
                };

            List<string> finals = new List<string>()
                {
                    user.UserBet.Finalist1Color,
                    user.UserBet.Finalist2Color
                };

            int numberOfQualified = 0;
            foreach (var qualify in qualified)
            {
                if (qualify == "green")
                {
                    numberOfQualified += 1;
                }
            }

            int numberOfQuarterfinals = 0;
            foreach (var quarterfinal in quarterfinals)
            {
                if (quarterfinal == "green")
                {
                    numberOfQuarterfinals += 1;
                }
            }

            int numberOfSemifinals = 0;
            foreach (var semiFinal in semiFinals)
            {
                if (semiFinal == "green")
                {
                    numberOfSemifinals += 1;
                }
            }

            int numberOfFinals = 0;
            foreach (var final in finals)
            {
                if (final == "green")
                {
                    numberOfFinals += 1;
                }
            }
            standing.NumberOfQualified = numberOfQualified;
            standing.NumberOfQuarterFinals = numberOfQuarterfinals;
            standing.NumberOfSemiFinals = numberOfSemifinals;
            standing.NumberOfFinals = numberOfFinals;
        }
    }
}

Awesome/Controllers/HomeController.cs
using System.Web.Mvc;
using Awesome.ApiIntegration.JsonGroupStageResult;
using Awesome.Models;
using Awesome.Models.ViewModel;

namespace Awesome.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            object message = string.Empty;

            FootballApiClient client = new FootballApiClient();
            JsonGroupStageResult groupStageMatches = client.GetGroupStageMatches();

            HomeViewModel currentViewModel = new HomeViewModel(groupStageMatches);
            ViewData["Logout"] = TempData["Logout"];

            if (TempData.TryGetValue("signuperror", out message))
            {
                currentViewModel.SignupErrorMessage = message.ToString();
            }
            if (TempData.TryGetValue("loginerror", out message))
            {
                currentViewModel.LoginErrorMessage = message.ToString();
            }

            return View(currentViewModel);
        }

        public ActionResult Standings()
        {
            ViewBag.Message = "Tabellen.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [Authorize]
        public ActionResult Welcome()
        {
            return View();
        }


    }
}

Awesome/Controllers/PlayerBetController.cs
using System.Web.Mvc;
using Awesome.ApiIntegration.JsonGroupStageResult;
using Awesome.ApiIntegration.JsonTeamResult;
using Awesome.Models;
using Awesome.Models.ViewModel;

namespace Awesome.Controllers
{
    public class PlayerBetController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            FootballApiClient client = new FootballApiClient();
            JsonGroupStageResult groupStageMatches = client.GetGroupStageMatches();
            JsonTeamResult teams = client.GetTeams();

            MyPageViewModel currentGamlePage = new MyPageViewModel(teams, groupStageMatches, null);

            return View(currentGamlePage);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Index(string userName)
        {
            FootballApiClient client = new FootballApiClient();
            JsonGroupStageResult groupStageMatches = client.GetGroupStageMatches();
            JsonTeamResult teams = client.GetTeams();

            MyPageViewModel currentGamlePage = new MyPageViewModel(teams, groupStageMatches, userName);

            return View(currentGamlePage);
        }
    }
}

Awesome/Views/Home/Index.cshtml
@using Awesome.Models.ViewModel
@model Awesome.Models.ViewModel.HomeViewModel
@{
    ViewBag.Title = "VM Tipset 2022";
    Layout = "~/Views/Shared/_Layout.cshtml";

}



<header class="intro">
    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h1 class="brand-heading">VM Tipset 2022</h1>
                    <p class="intro-text">
                        @ViewData["Logout"]
                        @if (@ViewData["Logout"] == null)
                        {
                            @String.Format("Ingen kommer ihåg en fegis!")
                        }
                    </p>
                    @if (ViewContext.HttpContext.User.Identity.IsAuthenticated)
                    {
                        <a href="#standings" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    }
                    else
                    {
                        <a class="page-scroll btn btn-primary" href="#login" id="loginButton">Logga in</a>
                        <a class="page-scroll btn btn-primary" href="#signup" id="signupButton">Registrera</a>
                    }

                </div>
            </div>
        </div>
    </div>
</header>

@*<section id="summary" class="container content-section summary">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            @Html.Partial("SummaryPartial", Model)
        </div>
    </div>
</section>*@


<section id="standings" class="container content-section standings">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            @Html.Partial("StandingsPartial", Model)
            </div>
        </div>
</section>

<section id="schedule" class="container content-section">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            @Html.Partial("SchedulePartial", Model)
        </div>
    </div>
</section>

<section id="rules" class="container content-section text-center">

    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            @Html.Partial("RulesPartial")
        </div>
    </div>
</section>


<section id="login" class="container content-section text-center" hidden>

    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            @if (!User.Identity.IsAuthenticated)
            {
                @Html.Partial("~/Views/Account/LogIn.cshtml", new UserLoginView(Model.LoginErrorMessage))
            }


        </div>
    </div>  
</section>

<section id="signup" class="container content-section text-center" hidden>
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            @if (!User.Identity.IsAuthenticated)
            {
                @Html.Partial("~/Views/Account/SignUp.cshtml", new UserSignUpView(Model.SignupErrorMessage))
            }
          

        </div>
    </div>
</section>


<script>
 

    $(document).ready(function () {



    });

    $("#loginButton").click(function () {
        $('#signup').hide();
        $('#login').show();
    });

    $("#signupButton").click(function () {
        $('#login').hide();
        $('#signup').show();
    });

</script>

Awesome/Views/Home/RulesPartial.cshtml
<div class="col-md-12">
    <h2>Regler</h2>
</div>
<div class="col-md-4">
    <h4 style="padding-top: 20px">1. Tippa</h4>
    <div class="text-left">
        Skapa en användare och tippa EMs alla gruppspelsmatcher inklusive åttondelslag, kvartsfinallag, semifinallag och finallag.
        <br /> <br /> Du har fram till 11:e juni på dig att fila på den bästa raden. Resultaten räknas ihop i en tabell enligt poängräkningen till höger.
    </div>
</div>
<div class="col-md-4">

    <h4 style="padding-top: 20px">2. Få Poäng</h4>
    <div>
        Tabellen räknas ut enligt följande:
        <div style="padding: 10px" class="text-left">
            <table>
                <tr>
                    <td>Rätt resultat: </td>
                    <td> 3 poäng</td>
                </tr>
                <tr>
                    <td>Rätt 1 X 2: </td>
                    <td> 1 poäng</td>
                </tr>
                <tr>
                    <td>Rätt åttondelslag: </td>
                    <td> 2 poäng</td>
                </tr>
                <tr>
                    <td>Rätt kvartsfinallag: </td>
                    <td> 3 poäng</td>
                </tr>
                <tr>
                    <td>Rätt semifinallag: </td>
                    <td> 5 poäng</td>
                </tr>
                <tr>
                    <td>Rätt finallag: </td>
                    <td> 7 poäng</td>
                </tr>
            </table>

        </div>
        Vid lika resultat gäller det att ha närmast gissning i antal gjorda mål under turneringen (exlusive straffavgöranden).
    </div>

</div>
<div class="col-md-4">

    <h4 style="padding-top: 20px">3. Vinn </h4>
    <div class="text-left">
        De 200kr varje deltagare betalar går oavkortat till prispotten, vilken delas upp så här:
        <div style="padding: 10px">
            <table>
                <tr>
                    <td>
                        1:a pris 50%
                    </td>
                </tr>
                <tr>
                    <td>
                        2:a pris 30%
                    </td>
                </tr>
                <tr>
                    <td>
                        3:e pris 20%
                    </td>
                </tr>
            </table>
        </div>
    </div>



</div>

Awesome/Views/Home/SchedulePartial.cshtml
@using System.Security.Policy
<h2 class="text-center">Spelschema</h2>



<table class="table noBorder">

    @if (Model.Matches != null)
    {
        foreach (var group in Model.Matches)
        {
            <thead>
                <tr class="text-center">
                    <th class="noBorder" colspan="8">@group[0].Date</th>

                </tr>
            </thead>


            foreach (var match in group)
            {
                <tbody>
                    <tr>
                        <td class="noBorder">@match.Time</td>

                        <td class="noBorder text-right hidden-xs">
                            @match.HomeTeam
                        </td>

                        <td class="flag-@match.HomeTeam.Replace(" ", "_") noBorder" style="height: 40px; border-top: none;" title="@match.HomeTeam"></td>
                        <td class="noBorder">
                            vs
                        </td>
                        <td class="flag-@match.AwayTeam.Replace(" ", "_") noBorder" style="height: 40px; border: none;" title="@match.AwayTeam"></td>
                        <td class="noBorder text-left hidden-xs">
                            @match.AwayTeam
                        </td>




                        @if (match.Status == "FINISHED")
                        {
                            <td class="noBorder">
                                @match.HomeScore -
                                @match.AwayScore
                            </td>
                        }
                        else
                        {
                            <td class="noBorder"></td>
                        }


                    </tr>
                </tbody>
            }


        }

    }

</table>

Awesome/Views/Home/StandingsPartial.cshtml
<h2 class="text-center">Tabell</h2>
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Namn</th>
            <th>0p</th>
            <th>1p</th>
            <th>3p</th>
            <th>Å</th>
            <th>K</th>
            <th>S</th>
            <th>F</th>
            <th>Tot</th>
        </tr>
    </thead>
    @if (ViewContext.HttpContext.User.Identity.IsAuthenticated)
    {
    <tbody>
        @{ int i = 1; }
        @foreach (var item in Model.ResultTable)
    {
        using (Html.BeginForm("Index", "PlayerBet", FormMethod.Post, new { id = "form-id-"+i , action = "PlayerBet#bet"}))
        {
            <tr class="zoom-small" onclick="postUser('form-id-@i')">
                <td>@i</td>
                <td title="@item.RealName">@item.LoginName</td>
                <td>@item.NumberOfZeroPoints</td>
                <td>@item.NumberOfOnePoints</td>
                <td>@item.NumberOfThreePoints</td>
                <td>@item.NumberOfQualified</td>
                <td>@item.NumberOfQuarterFinals</td>
                <td>@item.NumberOfSemiFinals</td>
                <td>@item.NumberOfFinals</td>
                <td>@item.TotalPoints</td>
            </tr>
            <input type="hidden" name="userName" value="@item.LoginName" />
             }

    i++;

}
    </tbody>

    }
    else
    {
        <tbody>
            @{ int i = 1; }
            @foreach (var item in Model.ResultTable)
            {
                <tr>
                    <td>@i</td>
                    <td title="@item.RealName">@item.LoginName</td>
                    <td>@item.NumberOfZeroPoints</td>
                    <td>@item.NumberOfOnePoints</td>
                    <td>@item.NumberOfThreePoints</td>
                    <td>@item.NumberOfQualified</td>
                    <td>@item.NumberOfQuarterFinals</td>
                    <td>@item.NumberOfSemiFinals</td>
                    <td>@item.NumberOfFinals</td>
                    <td>@item.TotalPoints</td>
                </tr>
                i++;
            }
        </tbody>
    }
</table>
@if (DateTime.Now < new DateTime(2021, 6, 11, 21, 0, 0))
{
    <table class="table">
        <thead>
            <tr>
                <th>Väntar på tips från...</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.UsersWithNoBet)
            {
                <tr>
                    <td title="@item.FirstName @item.LastName">@item.LoginName </td>
                </tr>
            }
        </tbody>
        <thead>
            <tr>
                <th>Lämna in senast 11 Juni 21:00 för att vara med!</th>
            </tr>
        </thead>
    </table>
}
<script>
   function postUser(value) {
        document.getElementById(value).submit();
    };
</script>

Awesome/Views/Home/SummaryPartial.cshtml
<h2 class="text-center">Slutsummering</h2>

<div class="col-md-12">
    Då var ett fotbolls VM åter till ända och så även tipset. Det största frågetecknet som vi lämnar bakom oss är hur storfavoriten Godden kunde komma så jättesist?! Jag har tyvärr inget bra svar utan kan bara konstatera att det, trots en viss tomhet, känns skönt att det är över, för då kan inget gå åt helvete längre.<br /><br /> 
    Vi var nog många som tidigt siktade in oss på en andraplats efter snipe_rdevils oanade bettingkunskaper. Han gick länge som tåget, men som vi alla vet så stannar dom för eller senare.
    <br /><br />
    Slutspelet började. Marcus tog över ledningen och höll undan. Han kunde till och med kosta på sig ett Panama i kvartsfinal, kaxigt eller klantigt? Säkert är att ingen kommer ihåg en fegis. Stort grattis!!<br /><br />
    Lurade i vassen gjorde länge JSandlake. Efter en fin fin upphämtning under slutspelets andra hälft spurtade han om alla utom en och slutar på en andra plats. Hatten av!<br /><br />
    masterwizard kniper tredjeplatsen efter ett riktigt pallplatsdrama. 4 spelare slutade på samma poäng och utslagsfrågan fick därför fälla avgörandet. <br /><br />
    Till oss andra mindre lyckosamma så hoppas jag ändå att ni haft roligt och att tipset har givit en liten extra krydda under mästerskapet. Tack för den här gången och hoppas vi ses när det är dags igen! <br /><br />
</div>