Awesome/Controllers/MyPageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Formatters.Binary;
using System.Web.Mvc;
using Awesome.ApiIntegration.JsonGroupStageResult;
using Awesome.ApiIntegration.JsonTeamResult;
using Awesome.Models;
using Awesome.Models.DB;
using Awesome.Models.EntityManager;
using Awesome.Models.ViewModel;

namespace Awesome.Controllers
{

    public class MyPageController : Controller
    {
        public static byte[] ObjectToByteArray(Object obj)
        {
            BinaryFormatter bf = new BinaryFormatter();
            using (var ms = new MemoryStream())
            {
                bf.Serialize(ms, obj);
                return ms.ToArray();
            }
        }

        [HttpPost]
        public ActionResult PlaceBet(MyPageViewModel placedBet, string username)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "The password provided is incorrect.");
                return new RedirectResult(Url.Action("Index") + "#bet");
            }

            UserBet userBet = new UserBet();

            foreach (var bet in placedBet.Bet.Matches)
            {
                Models.DB.Match match = new Models.DB.Match()
                {
                    HomeTeam = bet.HomeTeam,
                    AwayTeam = bet.AwayTeam,
                    HomeScore = bet.HomeScore,
                    AwayScore = bet.AwayScore
                };

                userBet.Matches.Add(match);
                userBet.Finalist1 = placedBet.Bet.Finalist1;
                userBet.Finalist2 = placedBet.Bet.Finalist2;
                userBet.Semifinalist1 = placedBet.Bet.Semifinalist1;
                userBet.Semifinalist2 = placedBet.Bet.Semifinalist2;
                userBet.Semifinalist3 = placedBet.Bet.Semifinalist3;
                userBet.Semifinalist4 = placedBet.Bet.Semifinalist4;
                userBet.QuarterFinalist1 = placedBet.Bet.QuarterFinalist1;
                userBet.QuarterFinalist2 = placedBet.Bet.QuarterFinalist2;
                userBet.QuarterFinalist3 = placedBet.Bet.QuarterFinalist3;
                userBet.QuarterFinalist4 = placedBet.Bet.QuarterFinalist4;
                userBet.QuarterFinalist5 = placedBet.Bet.QuarterFinalist5;
                userBet.QuarterFinalist6 = placedBet.Bet.QuarterFinalist6;
                userBet.QuarterFinalist7 = placedBet.Bet.QuarterFinalist7;
                userBet.QuarterFinalist8 = placedBet.Bet.QuarterFinalist8;
                userBet.Qualified1 = placedBet.Bet.Qualified1;
                userBet.Qualified2 = placedBet.Bet.Qualified2;
                userBet.Qualified3 = placedBet.Bet.Qualified3;
                userBet.Qualified4 = placedBet.Bet.Qualified4;
                userBet.Qualified5 = placedBet.Bet.Qualified5;
                userBet.Qualified6 = placedBet.Bet.Qualified6;
                userBet.Qualified7 = placedBet.Bet.Qualified7;
                userBet.Qualified8 = placedBet.Bet.Qualified8;
                userBet.Qualified9 = placedBet.Bet.Qualified9;
                userBet.Qualified10 = placedBet.Bet.Qualified10;
                userBet.Qualified11 = placedBet.Bet.Qualified11;
                userBet.Qualified12 = placedBet.Bet.Qualified12;
                userBet.Qualified13 = placedBet.Bet.Qualified13;
                userBet.Qualified14 = placedBet.Bet.Qualified14;
                userBet.Qualified15 = placedBet.Bet.Qualified15;
                userBet.Qualified16 = placedBet.Bet.Qualified16;
                userBet.TopScorer = placedBet.Bet.TopScorer;
                userBet.TotalGoals = placedBet.Bet.TotalGoals;

            }
            if (!this.IsValidUserBet(placedBet.Bet))
            {
                if (base.TempData["Fail"] == null)
                {
                    base.TempData.Add("Fail", "N\x00e5got blev tokigt, f\x00f6rs\x00f6k igen. T\x00e4nk p\x00e5 att ange olika lag i åttondelsfinal, kvartsfinal, semifinal och final.");
                }
                return new RedirectResult(base.Url.Action("Index") + "#bet");
            }
            UserManager.AddBet(userBet, username);
            if (base.TempData["Thanks"] == null)
            {
                base.TempData.Add("Thanks", "Tack f\x00f6r spelet");
            }
            return new RedirectResult(base.Url.Action("Index"));
        }

        [Authorize]
        public ActionResult Index()
        {
            FootballApiClient client = new FootballApiClient();
            JsonGroupStageResult groupStageMatches = client.GetGroupStageMatches();
            JsonTeamResult teams = client.GetTeams();

            MyPageViewModel currentGamlePage = new MyPageViewModel(teams, groupStageMatches, null);
            
            return View(currentGamlePage);            
        }

        [HttpPost]
        [Authorize]
        public ActionResult Index(string userName)
        {
            FootballApiClient client = new FootballApiClient();
            JsonGroupStageResult groupStageMatches = client.GetGroupStageMatches();
            JsonTeamResult teams = client.GetTeams();

            MyPageViewModel currentGamlePage = new MyPageViewModel(teams, groupStageMatches, userName);

            return View(currentGamlePage);
        }

        public bool IsValidUserBet(Bet bet)
        {
            List<string> list = new List<string>();
            List<string> list2 = new List<string> {
                bet.QuarterFinalist1,
                bet.QuarterFinalist2,
                bet.QuarterFinalist3,
                bet.QuarterFinalist4,
                bet.QuarterFinalist5,
                bet.QuarterFinalist6,
                bet.QuarterFinalist7,
                bet.QuarterFinalist8
            };
            List<string> list3 = new List<string>()
            {
                bet.Qualified1,
                bet.Qualified2,
                bet.Qualified3,
                bet.Qualified4,
                bet.Qualified5,
                bet.Qualified6,
                bet.Qualified7,
                bet.Qualified8,
                bet.Qualified9,
                bet.Qualified10,
                bet.Qualified11,
                bet.Qualified12,
                bet.Qualified13,
                bet.Qualified14,
                bet.Qualified15,
                bet.Qualified16,
        };
            list.Add(bet.Semifinalist1);
            list.Add(bet.Semifinalist2);
            list.Add(bet.Semifinalist3);
            list.Add(bet.Semifinalist4);

            var duplicateSemiTeams = list.GroupBy(x => x)
                .Where(group => group.Count() > 1)
                .Select(group => group.Key).Any();
            var duplicateQuarterTeams = list2.GroupBy(x => x)
                .Where(group => group.Count() > 1)
                .Select(group => group.Key).Any();
            var duplicateQualifiedTeams = list3.GroupBy(x => x)
                .Where(group => group.Count() > 1)
                .Select(group => group.Key).Any();

            return !duplicateSemiTeams && !duplicateQuarterTeams && !duplicateQualifiedTeams && (bet.Finalist1 != bet.Finalist2);

        }
    }
}

Awesome/Views/Shared/_Layout.cshtml
@using System.Diagnostics.Eventing.Reader
@using System.Web.UI.WebControls
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <title>@ViewBag.Title</title>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    <link rel="shortcut icon" type="image/png" href="https://www.favicon.cc/logo3d/142304.png" />
    <link href="/Content/css/bootstrap.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/Content/css/grayscale.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <i class="fa fa-play-circle"></i>  <span class="light">VM Tipset 2022</span>
                </a>
            </div>
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">

                <ul class="nav navbar-nav">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>

                    @if (Request.Url.AbsoluteUri == "https://www.tipset.azurewebsites.net/") //Ändra till faktisk url
    {
                <li> <a class="page-scroll" href="#page-top">Start</a></li>
              //<li> <a class="page-scroll" href="#page-top">Slutsummering</a></li>
                <li> <a class="page-scroll" href="#standings">Tabell</a></li>
                <li> <a class="page-scroll" href="#schedule">Spelschema</a></li>
                <li> <a class="page-scroll" href="#rules">Regler</a></li>
if (ViewContext.HttpContext.User.Identity.IsAuthenticated)
{
                <li id="dropDownList" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@User.Identity.Name <span class="caret"></span></a>
                    <ul class="dropdown-menu">

                        <li>@Html.ActionLink("Mitt spel", "Index", "MyPage", null, null, "bet", null, null)</li>

                        @if (ViewContext.HttpContext.User.IsInRole("Admin"))
        {
                <li role="separator" class="divider"></li>
                <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
}
                        <li role="separator" class="divider"></li>
                        <li>@Html.ActionLink("Logga ut", "SignOut", "Account")</li>
                    </ul>
                </li>
}

}
else
{
                <li>@Html.ActionLink("Start", "Index", "Home")</li>
                //<li>@Html.ActionLink("Slutsummering", "Index", "Home", null, null, "summary", null, null)</li>
                <li>@Html.ActionLink("Tabell", "Index", "Home", null, null, "standings", null, null)</li>
                <li>@Html.ActionLink("Spelschema", "Index", "Home", null, null, "schedule", null, null)</li>
                <li>@Html.ActionLink("Regler", "Index", "Home", null, null, "rules", null, null)</li>


if (ViewContext.HttpContext.User.Identity.IsAuthenticated)
{

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@User.Identity.Name<span class="caret"></span></a>
                    <ul class="dropdown-menu">

                        <li>@Html.ActionLink("Mitt spel", "Index", "MyPage", null, null, "bet", null, null)</li>

                        @if (ViewContext.HttpContext.User.IsInRole("Admin"))
        {
                <li role="separator" class="divider"></li>
                <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
}
                        <li role="separator" class="divider"></li>
                        <li>@Html.ActionLink("Logga ut", "SignOut", "Account")</li>
                    </ul>
                </li>
}
}

                </ul>
            </div>
        </div>
    </nav>

    @RenderBody()
    <!-- Footer -->
    <footer>
        <div class="text-center footer">

        </div>
    </footer>
    <!-- jQuery -->
    <script src="/Content/js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/Content/js/bootstrap.js"></script>
    <!-- Plugin JavaScript -->
    <script src="/Content/js/jquery.easing.min.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="/Content/js/grayscale.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Content/js/main.js"></script>
</body>
</html>